services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432 # enables connecting locally via psql
    environment:
      POSTGRES_DB: taskmanager_dev
      POSTGRES_PASSWORD: nigutenisawa
      POSTGRES_USER: samdev
      # POSTGRES_HOST_AUTH_METHOD: trust
